### ISSUE TITLE
Error: Class 'Cassandra' not found in /engine/Core/Data/Cassandra/Client.php:23

### ISSUE THREAD

**Issue by nasservb** [Minds/minds#62]
i fixing that error in main page by some change : 
```php
<?php
/**
 * Cassandra client
 */
namespace Minds\Core\Data\Cassandra;

use Cassandra as Driver;
use Minds\Core;
use Minds\Core\Data\Interfaces;
use Minds\Core\Config;

class Client implements Interfaces\ClientInterface
{
    private $cluster;
    private $session;
    private $prepared;
    protected $debug;

    public function __construct(array $options = array())
    {
        $options = array_merge((array) Config::_()->cassandra, $options);

		$oReflectionClass = new \ReflectionClass('Cassandra'); 
		
        $this->cluster = \Cassandra::cluster()
           ->withContactPoints(... $options['cql_servers'])
           ->withPort(9042)
           ->build();
		   
        $this->session = $this->cluster->connect($options['keyspace']);

        $this->debug = (bool) Core\Di\Di::_()->get('Config')->get('minds_debug');
    }

    public function request(Interfaces\PreparedInterface $request, $silent = false)
    {
        $cql = $request->build();
        try{
            $statement = $this->session->prepare($cql['string']);
            $future = $this->session->executeAsync(
              $statement,
              new \Cassandra\ExecutionOptions(array_merge(
                  [
                    'arguments' => $cql['values']
                  ],
                  $request->getOpts()
                  ))
            );
            if (!$silent) {
              return $response = $future->get();
            }
        }catch(\Exception $e){
            if ($this->debug) {
                error_log('[CQL Error: ' . get_class($e) . '] ' . $e->getMessage());
                error_log(json_encode($cql));
            }
            return false;
        }

        return true;
    }

    public function batchRequest($requests = array())
    {
        $batch = new \Cassandra\BatchStatement(Driver::BATCH_COUNTER);

        foreach ($requests as $request) {
            $cql = $request;
            $statement = $this->session->prepare($cql['string']);
            $batch->add($statement, $cql['values']);
        }

        return $session->execute($batch);
    }

    public function getPrefix()
    {
        return Config::_()->get('multi')['prefix'];
    }
}


```

but when i saw my log  : 
```
017/09/15 18:24:13 [error] 14454#14454: *453 FastCGI sent in stderr: "PHP message: Exception #1505483653: ReflectionException: Class Cassandra does not exist in /var/www/Minds/engine/Core/Data/Cassandra/Client.php:24
Stack trace:
#0 /var/www/Minds/engine/Core/Data/Cassandra/Client.php(24): ReflectionClass->__construct('Cassandra')
#1 /var/www/Minds/engine/Core/Data/DataProvider.php(36): Minds\Core\Data\Cassandra\Client->__construct()
#2 [internal function]: Minds\Core\Data\DataProvider->Minds\Core\Data\{closure}(Object(Minds\Core\Di\Di))
#3 /var/www/Minds/engine/Core/Di/Di.php(25): call_user_func(Object(Closure), Object(Minds\Core\Di\Di))
#4 /var/www/Minds/engine/Core/Search/Tagcloud.php(25): Minds\Core\Di\Di->get('Database\\Cassan...')
#5 /var/www/Minds/engine/Controllers/api/v1/search/tagcloud.php(20): Minds\Core\Search\Tagcloud->__construct()
#6 /var/www/Minds/engine/Api/Factory.php(69): Minds\Controllers\api\v1\search\tagcloud->get(Array)
#7 /var/www/Minds/engine/Controllers/api/api.php(50): Minds\Api\Factory::build(Array)
#8 /var/www/Minds/engine/Core/Router.php(79): M" while reading response header from upstream, client: 151.240.188.234, server: _, request: "GET /api/v1/search/tagcloud? HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:",
```

**Comment by markharding** [comment]
Please make sure you have run composer install before hand. Thanks!

**Comment by nasservb** [comment]
i run composer install and done successful . 
```
root@af01:/var/www/Minds/engine# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.
Package graphaware/neo4j-response-formatter is abandoned, you should avoid using it. No replacement was suggested.
Package neoxygen/neoclient is abandoned, you should avoid using it. Use graphaware/neo4j-php-client instead.
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Generating autoload files

```
and then when i run my home page that error wrote in nginx error log : 
```
2017/09/15 23:37:21 [error] 14454#14454: *865 FastCGI sent in stderr: "PHP message: Exception #1505502441: Error: Class 'Cassandra' not found in /var/www/Minds/engine/Core/Data/Cassandra/Client.php:25
Stack trace:
#0 /var/www/Minds/engine/Core/Data/Client.php(34): Minds\Core\Data\Cassandra\Client->__construct(Array)
#1 /var/www/Minds/engine/Helpers/Counters.php(133): Minds\Core\data\Client::build('\\Minds\\Core\\Dat...')
#2 /var/www/Minds/engine/Core/Navigation/Manager.php(163): Minds\Helpers\Counters::get(755372364346167313, 'points', false)
#3 /var/www/Minds/engine/Core/Navigation/Manager.php(225): Minds\Core\Navigation\Manager::defaults()
#4 /var/www/Minds/front/public/index.php(131): Minds\Core\Navigation\Manager::export()
#5 /var/www/Minds/engine/Core/Router.php(88): include('/var/www/Minds/...')
#6 /var/www/Minds/index.php(9): Minds\Core\Router->route()
#7 {main}
```

i clone and compile cpp_driver,libuv and install cassandra by pecl install cassandra  .
my php find cassandra : 

```
 php -i | grep cassandra
/etc/php/7.0/cli/conf.d/20-cassandra.ini,
cassandra
cassandra.log => cassandra.log => cassandra.log
cassandra.log_level => ERROR => ERROR
```
when i run cli.php installer that file is run without any erro . 
tank you for pay attention and lovely project .
